### ISSUE TITLE
Error '404  on /' routing

### ISSUE THREAD

**Issue by vandelpavel** [freddy38510/quasar-app-extension-ssg#17] opened 2020-08-17 16:39 UTC
Inside a project i have different pages and a layout defined as in `routes.js`:

```js
const routes = [
  {
    path: '/',
    component: () => import('layouts/MainLayout.vue'),
    children: [
      { path: '', component: () => import('pages/Test.vue') },
      { path: 'Home', component: () => import('pages/Test.vue') },
],
  },
  { path: '*', component: () => import('pages/error-404.vue') },
];

export default routes;
```

So i modified the `quasar.conf.js`  with `vueRouterMode: 'history'`.

Then i added the routes in `src-ssg.routes.js`:

```js
module.exports = function() {
  return ['/', '/home'];
};
```

Then i launch  `quasar ssg build` and then `quasar serve dist/ssr/www/`.

No error yet but when reaching `localhost:4000` the console's output is:
`GET / [127.0.0.1] Mon Aug 17 2020 18:20:28 GMT+0200 (GMT+02:00)
  404 on /`

Even when changing routes and typing `localhost:4000/home` the console will show `404 on /home`.

Any ideas?

**Comment by freddy38510** [comment] 2020-08-17 17:41
I can't reproduce it.

I tried with your repository https://github.com/vandelpavel/app-esxtension-test.git

I made all the modifications you did, the two routes are generated well. I've got no 404 on them.

**Comment by vandelpavel** [comment] 2020-08-18 09:50
Actually yes, on the repository i made it works just fine. The problem is when i try to do it in my actual project. I can't see where the problem could be...
The only thing i discovered it's that after building the ssg if i use `quasar serve dist/ssr/www/` it doesn't even show the home page and keeps saying `404 on /` but if i use `npx http-server dist/ssr/www/` it works and i can't see why...
Here is my `quasar.conf.js` file probably i'm missing something here...

```js
/* eslint-env node */
// Configuration for your app
// https://quasar.dev/quasar-cli/quasar-conf-js
/* eslint-env node */

const { configure } = require('quasar/wrappers');

// TODO: define this into `build > distDir` once and take it from webpack config for other needs
const DIST_DIR = 'dist/spa/public';

module.exports = configure(function(ctx) {
  return {
    sourceFiles: {
      // Default is `src/App.vue`, but we prefer lowercase for components names (and Linux is case sensitive)
      rootComponent: 'src/app.vue',
    },

    // app boot file (/src/boot)
    // --> boot files are part of "main.js"
    // https://quasar.dev/quasar-cli/cli-documentation/boot-files
    boot: ['axios'],

    // https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-css
    css: ['app.scss'],

    // https://github.com/quasarframework/quasar/tree/dev/extras
    extras: [
      // 'ionicons-v4',
      // 'mdi-v4',
      // 'fontawesome-v5',
      // 'eva-icons',
      // 'themify',
      // "roboto-font", // optional, you are not bound to it
      // 'roboto-font-latin-ext', // this or either 'roboto-font', NEVER both!

      'material-icons', // optional, you are not bound to it
    ],

    // https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-framework
    framework: {
      iconSet: 'material-icons', // Quasar icon set
      lang: 'it', // Quasar language pack

      importStrategy: 'auto',

      components: [],
      directives: [],

      // Quasar plugins
      plugins: ['Meta'],
    },

    // https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-build
    build: {
      distDir: DIST_DIR,

      env: ctx.prod
        ? {
            APP_DOMAIN: 'https://www.athenia-net.it',
          }
        : {},

      scopeHoisting: true,
      vueRouterMode: 'history',
      transpileDependencies: [/@dreamonkey[\\/]quasar-app-extension-animate/],
      // showProgress: false,
      // gzip: true,
      // analyze: true,
      // preloadChunks: false,
      // extractCSS: false,

      // https://quasar.dev/quasar-cli/cli-documentation/handling-webpack
      extendWebpack(cfg) {
        cfg.module.rules.push({
          test: /\.vue$/,
          loader: 'vue-svg-inline-loader',
          options: {
            addTitle: true,
          },
        });
       
      },
    },

    // https://quasar.dev/quasar-cli/quasar-conf-js#Property%3A-devServer
    devServer: {
      // https: true,
      // port: 8080,
      open: true, // opens browser window automatically
    },

    // animations: 'all', // --- includes all animations
    // https://quasar.dev/options/animations
    animations: ['fadeInDown', 'zoomIn', 'fadeInLeft', 'fadeIn', 'fadeInUp'],

    // https://quasar.dev/quasar-cli/developing-ssr/configuring-ssr
    ssr: {
      pwa: false,
    },

    // https://quasar.dev/quasar-cli/developing-pwa/configuring-pwa
    pwa: {
      // workboxPluginMode: 'InjectManifest',
      // workboxOptions: {}, // only for NON InjectManifest
      manifest: {
        // name: 'Athenia',
        // short_name: 'Athenia',
        // description: 'A Quasar Framework app',
        display: 'standalone',
        orientation: 'portrait',
        background_color: '#ffffff',
        theme_color: '#027be3',
        icons: [
          {
            src: 'icons/icon-128x128.png',
            sizes: '128x128',
            type: 'image/png',
          },
          {
            src: 'icons/icon-192x192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: 'icons/icon-256x256.png',
            sizes: '256x256',
            type: 'image/png',
          },
          {
            src: 'icons/icon-384x384.png',
            sizes: '384x384',
            type: 'image/png',
          },
          {
            src: 'icons/icon-512x512.png',
            sizes: '512x512',
            type: 'image/png',
          },
        ],
      },
    },

    // https://quasar.dev/quasar-cli/developing-cordova-apps/configuring-cordova
    cordova: {
      // id: 'org.dreamonkey.athenia.website',
      // noIosLegacyBuildFlag: true, // uncomment only if you know what you are doing
    },

    // https://quasar.dev/quasar-cli/developing-electron-apps/configuring-electron
    electron: {
      // bundler: 'builder', // or 'packager'

      extendWebpack(/* cfg */) {
        // do something with Electron main process Webpack cfg
        // chainWebpack also available besides this extendWebpack
      },

      packager: {
        // https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#options
        // OS X / Mac App Store
        // appBundleId: '',
        // appCategoryType: '',
        // osxSign: '',
        // protocol: 'myapp://path',
        // Windows only
        // win32metadata: { ... }
      },

      builder: {
        // https://www.electron.build/configuration/configuration
        // appId: 'athenia'
      },
    },
  };
});
```

**Comment by freddy38510** [comment] 2020-08-18 13:45
Can you show the content of your distDir please ?

I think the "index.html" files of your prerendered routes are not generated into your custom distDir `dist/spa/public`.

Shoudn't the command be `quasar serve dist/spa/public` instead of `quasar serve dist/ssr/www/` ?

**Comment by vandelpavel** [comment] 2020-08-18 13:57
Exactly they are not generated.
![image](https://user-images.githubusercontent.com/61196133/90521802-3ed33200-e16b-11ea-9515-109cacab0948.png)
I'v made same procedures as in the test dozen of times, tried to find where i was wrong but nothing yet...
Actually also `quasar serve dist/spa/public` doesn't work

**Comment by freddy38510** [comment] 2020-08-18 14:01
From your `quasar-conf.js` file you set `distDir` to `dist/spa/public`.

Please, run `quasar clean` then `quasar ssg build`.

After that, paste the output of the last command and show the content of `dist/spa/public`.

**Comment by vandelpavel** [comment] 2020-08-18 14:22
I've already set `distDir` to `dist/spa/public` in my quasar conf.

Here is the output after `quasar ssg build`:
```
$ quasar ssg build
 App · Looking for Quasar App Extension "ssg" command "build"
 App · Running "ssg" Quasar App Extension...
 App · Running "ssg" > "build" command


 Build mode........ ssr
 Pkg quasar........ v1.12.13
 Pkg @quasar/app... v2.0.6
 Debugging......... no
 Publishing........ no

 Configured browser support (at least 87.55% of global marketshare):
 · Chrome for Android >= 84
 · Firefox for Android >= 68
 · Android >= 81
 · Chrome >= 74
 · Edge >= 80
 · Firefox >= 70
 · IE >= 11
 · iOS >= 10.0-10.2
 · Opera >= 65
 · Safari >= 10.1

 App · Running "ssg" Quasar App Extension...
 App · Running "@dreamonkey/animate" Quasar App Extension...
 App · Reading quasar.conf.js
 App · Extension(ssg): Extending quasar.conf...
 App · Extension(@dreamonkey/animate): Extending quasar.conf...
 App · Transpiling JS (Babel active) - includes IE11 support
 App · Extension(ssg): Chaining Client Webpack config
 App · Extending Client Webpack config
 App · Extension(ssg): Chaining Server Webpack config
 App · Extending Server Webpack config
 App · Extension(ssg): Chaining Webserver Webpack config
 App · Cleaned build artifact: "C:\Users\Hp\Documents\Sources\athenia\dist\spa\public"
 App · Generating Webpack entry point
 App · Compiling with Webpack...

 • Compiling:
 ├── Client    ███                  10% building 2/2 modules 0 active
 ├── Server    ███                  10% building 7/7 modules 0 active
 └── Webserver ████████████████████ 100% done in 4806 ms


 • Compiling:
 ├── Client    ████████████████████ 95% emitting HtmlWebpackPlugin
 ├── Server    ████████████████████ 100% done in 25807 ms
 └── Webserver ████████████████████ 100% done in 4806 ms


 • Compiling:
 ├── Client    ████████████████████ 100% done in 25802 ms
 ├── Server    ████████████████████ 100% done in 25807 ms
 └── Webserver ████████████████████ 100% done in 4806 ms

 App · Added build artifact "C:\Users\Hp\Documents\Sources\athenia\dist\spa\public"

 Server summary for css/js/json (the rest are omitted):
 ╔═════════════════════════════╤══════════╤═════════╗
 ║                       Asset │     Size │ Gzipped ║
 ╟─────────────────────────────┼──────────┼─────────╢
 ║                package.json │  0.94 KB │ 0.43 KB ║
 ║ quasar.server-manifest.json │ 17.79 KB │ 6.17 KB ║
 ╚═════════════════════════════╧══════════╧═════════╝

 Client summary for css/js/json (the rest are omitted):
 ╔═════════════════════════════╤═══════════╤══════════╗
 ║                       Asset │      Size │  Gzipped ║
 ╟─────────────────────────────┼───────────┼──────────╢
 ║              1.b3bd23f1.css │   0.09 KB │  0.10 KB ║
 ║            app.e5622d72.css │  10.55 KB │  1.73 KB ║
 ║         vendor.6d97b2bb.css │ 204.28 KB │ 35.40 KB ║
 ║                   reset.css │   1.38 KB │  0.64 KB ║
 ╟─────────────────────────────┼───────────┼──────────╢
 ║               1.4c2355f0.js │   2.33 KB │  0.55 KB ║
 ║               3.f02ad294.js │   0.47 KB │  0.34 KB ║
 ║             app.9f626054.js │   7.09 KB │  3.11 KB ║
 ║          vendor.add4adf9.js │ 247.98 KB │ 86.77 KB ║
 ╟─────────────────────────────┼───────────┼──────────╢
 ║ quasar.client-manifest.json │  19.97 KB │  2.45 KB ║
 ╚═════════════════════════════╧═══════════╧══════════╝

 Webserver summary for css/js/json (the rest are omitted):
 ╔══════════╤══════════╤═════════╗
 ║    Asset │     Size │ Gzipped ║
 ╟──────────┼──────────┼─────────╢
 ║ index.js │ 11.16 KB │ 3.62 KB ║
 ║   ssr.js │  1.74 KB │ 0.83 KB ║
 ╚══════════╧══════════╧═════════╝

 Build succeeded

 Build mode........ ssr
 Pkg quasar........ v1.12.13
 Pkg @quasar/app... v2.0.6
 Debugging......... no
 Publishing........ no
 Transpiled JS..... yes (Babel) - includes IE11 support
 ==================
 Output folder..... C:\Users\Hp\Documents\Sources\athenia\dist\spa\public

 Tip: The output folder must be yarn/npm installed before using it,
      except when it is run inside your already yarn/npm installed project folder.

 Tip: Notice the package.json generated, where there's a script defined:
        "start": "node index.js"
      Running "$ yarn start" or "$ npm run start" from the output folder will
      start the webserver. Alternatively you can call "$ node index.js"
      yourself.

 App · Extension(ssg): Running afterBuild hook...
 Extension(ssg) · Generating route /...
 Extension(ssg) · Inlining critical Css for route /...
 Extension(ssg) · Inlined 189 B (13% of original 1.41 kB) of reset.css.
 Extension(ssg) · Inlined 867 B (0% of original 209 kB) of css/vendor.6d97b2bb.css.
 Extension(ssg) · Inlined 41 B (0% of original 10.8 kB) of css/app.e5622d72.css.
 Extension(ssg) · Generating route /home...
 Extension(ssg) · Inlining critical Css for route /home...
 Extension(ssg) · Inlined 189 B (13% of original 1.41 kB) of reset.css.
 Extension(ssg) · Inlined 867 B (0% of original 209 kB) of css/vendor.6d97b2bb.css.
 Extension(ssg) · Inlined 41 B (0% of original 10.8 kB) of css/app.e5622d72.css.
 Extension(ssg) · Inlining critical Css for fallback...
 Extension(ssg) · Inlined 189 B (13% of original 1.41 kB) of reset.css.
 Extension(ssg) · Inlined 788 B (0% of original 209 kB) of css/vendor.6d97b2bb.css.
 Extension(ssg) · Inlined 41 B (0% of original 10.8 kB) of css/app.e5622d72.css.
```

And here is the content of the folder:
![image](https://user-images.githubusercontent.com/61196133/90525028-11888300-e16f-11ea-8fa8-9b0509b17da8.png)

**Comment by freddy38510** [comment] 2020-08-18 15:56
All looks good for me.

It seems we simply missed the `www` folder.

Can you try to run `quasar serve dist/spa/public/www` ?

**Comment by vandelpavel** [comment] 2020-08-19 08:04
After `quasar ssg build` and `quasar serve dist/spa/public/www` no console errors but when loading the page for the first few second i see all the icons black filled and some text over the background then the page loads like noral.

The www folder:
![image](https://user-images.githubusercontent.com/61196133/90607784-ff0b5980-e201-11ea-9955-ea4c9637c383.png)

**Comment by freddy38510** [comment] 2020-08-19 11:59
It looks like a FOUC (Flash Of Unstyled Content).

Did you enable criticalCss from the extension ?

If you did you should also set `extractCSS` to `true` in quasar-conf.js 

For the preload strategy i recommend to set it to `media` as it seems to give the best performance.

If nothing of that avoid the FOUC, try to set `criticalCss.enable` to `false`.

PS: There are some commits that i will push soon. One of them will remove the critical CSS part, let it to the user's own choice with some hooks to post process prerendered pages like they want it.

**Comment by freddy38510** [comment] 2020-08-19 14:35
I close the issue as this is not related to the extension.

**Closed by freddy38510** 2020-08-19 14:35 UTC

**Comment by vandelpavel** [comment] 2020-08-19 15:12
Yes i enabled it when invoking the AE.
For the preload i opted for default, i'll try media thanks for the advice ;)
After setting `extractCSS `to `true ` and using `media` strategy it keeps doing like before.
I also tryied  setting criticalCss.enable to false and actually keeps doing the same.
I saw you committed some changes, i'll try do uninvoke the AE and try again following the new read me.

**Comment by vandelpavel** [comment] 2020-08-20 14:47
Actually i'm keep haveng the same `404 on /` error with the new version.
Also in the https://github.com/freddy38510/quasar-app-extension-ssg#routes part probably you forgot a `;` at the end.
Also options must go in quasar.conf or you can set them in quasar.extension.json inside the `ssg` block?

**Comment by vandelpavel** [comment] 2020-08-20 15:03
Ok probably you can't set them in quasar.extension.
Anyways...
I tried to create a fresh quasar project from scratch following your guide and after trying to put the routes both in quasar.con and quasar.extension i couldn't be able to make it work.

**Comment by freddy38510** [comment] 2020-08-20 15:10
Configuration are not parsed from `quasar.extensions.json`.

I think you edit the default `build.distDir` and you served files from the wrong folder.

Which command are you using to test the site ?

Which value have you set to `build.distDir` in `quasar-conf.js` file ?

**Comment by vandelpavel** [comment] 2020-08-20 15:30
No didn't edited dist dir this time and serving right folder.
i'm using `quasar ssg serve dist\ssg`
Yes i set my ports on quasar.consig.js.
There is a reason why you are writing quasar-conf instead of quasar.config? Probably i'm referencing to the wrong file

**Comment by vandelpavel** [comment] 2020-08-20 15:36
To reproduce create a new quasar project;
Execute:
`yarn add --dev https://github.com/freddy38510/quasar-app-extension-ssg`;
`quasar ext invoke ssg`;

Set the path you need in `quasar.conf`;
Execute `quasar ssg generate` and then serve it like so `quasar ssg serve dist\ssg`

**Comment by freddy38510** [comment] 2020-08-20 15:52
If you are typing `dist\ssg` it results to `distssg`.

You should use `quasar ssg serve dist/ssg`.

You are right about quasar config file. There is a dot instead of a dash, my bad.
Its right name is `quasar.conf.js`.

**Comment by vandelpavel** [comment] 2020-08-20 16:12
This time the folder have the home inner folder and should work fine...
![image](https://user-images.githubusercontent.com/61196133/90797230-aaa2cf80-e310-11ea-8f02-fca4b045eb76.png)

**Comment by freddy38510** [comment] 2020-08-20 17:37
I guess you are on Windows. I'm using Linux and the output tip is different from yours concerning `dist/ssg`.

Is it right ?

**Comment by vandelpavel** [comment] 2020-08-21 07:44
Yes i'm using windows but also using `/` doesn't make it works
